replicaCount: 2

image:
  repository: parallel-fetcher
  tag: "latest"
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "200m"
    memory: "128Mi"